apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: cafe
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: pradeepch82/tea:1.2
        name: guestbook-ui
        ports:
        - containerPort: 80
